### ISSUE TITLE
404 on valid routes

### ISSUE THREAD

**Issue by Marsup** [delvedor/find-my-way#110]
Hi,

I'm getting 404s on paths matching existing routes, it looks similar to #101 but I'm not sure it's the same issue so I'm creating a new one.

I only have a repro with fastify involved, hope you don't mind: https://runkit.com/embed/lx7pizmbgoru
There are several weird things in my example like a completely different path influencing the outcome, but it looks like the issue is with the variable part of the url starting like letters of another static route, at least that's my best guess.

I bisected until find-my-way 1.0.0 but it seems it's always been there, so it's not a regression.

**Comment by IpaliboWhyte** [comment]
Hey, I'll try to look into this as I've experienced a similar issue in the [past](https://github.com/delvedor/find-my-way/issues/104).

**Comment by mcollina** [comment]
Thanks @IpaliboWhyte!

**Comment by IpaliboWhyte** [comment]
@Marsup can you try the latest version?

**Comment by delvedor** [comment]
I didn’t released the latest version yet, for some reason is failing on master, and I didn’t have time to fix it yet.

**Comment by mcollina** [comment]
Tests are now passing on master.

**Comment by delvedor** [comment]
Released `v1.18.1`.

@Marsup can you check if the bug still persists?

**Comment by Marsup** [comment]
It appears to be working, thanks a lot!
