### ISSUE TITLE
hey, how can i read file ? like index.html

### ISSUE THREAD

**Issue by extremety1989** [delvedor/find-my-way#113]
i want to display index.html

router.on('GET', '/', (req, res, params) => {
  res.readFileSync('./index.html',function(err,data){
        if(err){res.statusCode = 404}else{
        res.statusCode = 200
        }
        res.end(data)     
  })
})
it says res.readFileSync it s not a function

**Comment by IpaliboWhyte** [comment]
@extremety1989  you need to use **fs** module to read the file. 

```
const fs = require('fs')
...
fs.readFileSync(...)
...
```

**Comment by delvedor** [comment]
Hello! As said by @IpaliboWhyte you should use Node.js's `fs` module.
This module is just an HTTP router, and it does not offer nothing more than routing :)
