### ISSUE TITLE
Idea: Allow registration of multiple routes at once through an array?

### ISSUE THREAD

**Issue by rw3iss** [delvedor/find-my-way#126]
Does anyone else think it would nice to supply an array of routes to 'router.on([...])' to register them all with one call?
This would be useful if I want to define my sub/type-specific routes in other files, and have to import them somewhere else to be registered with the main router.
Instead of having to manually register each route, the sub-file could return an array of the routes, and the router could register them all with router.on(Array).
Granted, I could just pass the router to the sub-file, and manually register each route to it, which I'm doing, so this is just a nice-to-have I think.
Anyone see a downside to that?

**Comment by IpaliboWhyte** [comment]
Hmm could be a nice feature but I think for the use case you've described, that could also be achieved with some abstraction outside of this module.

For example you could have a class that wraps the router instance and exposes a method that accepts a list of routes, then in your main file you would just call this method with an array all the pushed routes. 

Example:
```
class MyRouter{
  constructor(){
    this.router = require('find-my-way')()
  }
  buildRoutes(routes){
    // go through all routes and call this.router.on(...) 
  }
}
```

**Comment by rw3iss** [comment]
Sure, that's what I'm doing :p 
Was just thinking of an alternative interface, not really a big deal.
Thanks.

**Comment by delvedor** [comment]
Hello! I don't think it is worth add the support for this since it will increase the internal code complexity *(you can already do `router.on(['GET', 'POST'], ...)`)* and you can easily achieve it with a loop in your code :)
