### ISSUE TITLE
Returns routes registered without prettyPrint

### ISSUE THREAD

**Issue by RafaelGSS** [delvedor/find-my-way#127]
Hello!

Maybe can be interesting add to public API a method that returns the array of routes registered. ( this can help me in a plugin fastify - I know the hook `onRoute`, but this seems better. ).

Thx.

**Comment by delvedor** [comment]
You can access already the registered routes via `router.routes` :)
It's not documented because I never saw the use of this, but it's kind of public API 😄

**Comment by RafaelGSS** [comment]
I can expose in docs?

**Comment by delvedor** [comment]
Feel free to send a pr :)

**Comment by delvedor** [comment]
But if we expose this, we should also add a unit test ;)

**Comment by RafaelGSS** [comment]
Sure, when I have time here, I'll do it.
