### ISSUE TITLE
OPTIONS not working in this wildcard scenario

### ISSUE THREAD

**Issue by RaghavendhraK** [delvedor/find-my-way#132]
Hi,
With the below setup, the OPTIONS call is not working for the /obj/params/*, But the GET call works for the same.
Are we doing anything wrong with the setup?

```javascript
const FindMyWay = require("find-my-way");
const findMyWay = FindMyWay({
  ignoreTrailingSlash: true,
  defaultRoute: (req, res) => {
    console.error(req.method, req.url, "SHOULD NOT BE IN defaultRoute!!!!");
  }
});
findMyWay.on("OPTIONS", "/*", (req, res, params) => {
  console.info(req.method, req.url, "we should be here");
});
findMyWay.on("GET", "/obj/params/*", (req, res, params) => {
  console.info(req.method, req.url, "we should be here");
});
//When we comment this line, then also it works
findMyWay.on("GET", "/obj/:id", (req, res, params) => {
  console.info(req.method, req.url, "we should not be here");
});
findMyWay.on("GET", "/obj_params/*", (req, res, params) => {
  console.info(req.method, req.url, "we should be here");
});

console.log(findMyWay.prettyPrint());

//This works
findMyWay.lookup({ method: "OPTIONS", url: "/obj/params", headers: {} }, null);

//This doesn't works
findMyWay.lookup(
  { method: "OPTIONS", url: "/obj/params/12", headers: {} },
  null
);
//But this works
findMyWay.lookup({ method: "GET", url: "/obj/params/12", headers: {} }, null);

//This also works
findMyWay.lookup(
  { method: "OPTIONS", url: "/obj_params/12", headers: {} },
  null
);


```

Thanks,
Raghu

**Comment by delvedor** [comment]
Hello! You are right, this is a bug.
I'll try to give it a look as soon as I can, if you want to try to fix, please go ahead!

**Comment by delvedor** [comment]
The common root of the path causes the issue. Most of the edge cases are already covered, except for this one :S

A change that will solve this problem is to have a separate tree for every method, but this would break the `prettyPrint` method.
We can refactor `prettyPrint` to return an object that has the methods as keys and the values as the trees. I need to think about this since it would be a breaking change.

**Comment by delvedor** [comment]
I've opened https://github.com/delvedor/find-my-way/pull/133 with a fix for this bug.
Would you mind take a look?
