### ISSUE TITLE
no frills lookup: find-my-way leaner and meaner

### ISSUE THREAD

**Issue by jbemmel** [delvedor/find-my-way#139]
I like find-my-way and its minimalistic, no-frills approach. Here are some thoughts on making it even better:

The key function in find-my-way is '[lookup](https://github.com/delvedor/find-my-way/blob/master/index.js#L345)':
```javascript
    Router.prototype.lookup = function lookup (req, res, ctx) {
     var handle = this.find(req.method, sanitizeUrl(req.url), this.versioning.deriveVersion(req, ctx))
     if (handle === null) return this._defaultRoute(req, res, ctx)
     return ctx === undefined
      ? handle.handler(req, res, handle.params, handle.store)
       : handle.handler.call(ctx, req, res, handle.params, handle.store)
    }
```
* 'ctx' is optional and gets passed as 'this' to the handler
* 'handle.store' is an optional parameter passed to router.on( ... )
* My application does not need versioning

Passing 'this' doesn't work in case of arrow functions. To pass context from 'on(...)' users can easily do this:
```javascript
    function surroundingScope() {
       const store = "x";
       router.on( "GET", (req,res) => { use 'store' here, or any other variables } );
```

So how about adding:
```javascript
    Router.prototype.nofrills_lookup = (req, res, ctx) => {
     const handle = this.find(req.method, req.url )
     if (handle === null) return this._defaultRoute(req, res, ctx)
     return handle.handler(req, res, handle.params, ctx)
    }
```

* Can use arrow functions as handlers, 'ctx' passed as regular variable
* No versioning / optional context / store overhead
* Sanitizing URLs left to the user (could expose the function in the API, or suggest a more featureful package)
* Peacefully co-exists with existing lookup

**Comment by delvedor** [comment]
Hello!

> Passing 'this' doesn't work in case of arrow functions.

That's true, if you want to use the `this` you should use a "normal" function.

> To pass context from 'on(...)' users can easily do this:

It works, but passing the context via binding is more flexible while creating a closure is not always possible.

> No versioning / optional context / store overhead

If you are not using these features, there is no overhead.

> Sanitizing URLs left to the user (could expose the function in the API, or suggest a more featureful package)

The point of `lookup`, is to provide a convenient function that take care of everything for you.
If you want to use a different approach, you can directly use `find` and write your own business logic.

Closing for now, feel free to reopen if you have additional points you want to discuss!

**Comment by jbemmel** [comment]
Thanks, I switched to using [TrekJS](https://github.com/trekjs/router/blob/master/index.js) code directly
