### ISSUE TITLE
Make versioning truly optional

### ISSUE THREAD

**Issue by jbemmel** [delvedor/find-my-way#140]
In [this PR](https://github.com/delvedor/find-my-way/pull/107) versioning support was added. While this may be useful to some, not all applications require this, and it adds to the dependencies.

I would suggest to split this logic into a separate find-my-way-versioning package, and default to a no versioning approach (with no dependency on semver-store). If users want versioning support, they can do
```javascript
const _options = {
   versioning: require('find-my-way-versioning')
}
```

Something similar could be done for Regex safety checks: If a user wants that, they can add
```javascript
const _options = {
  isRegexSafe : require('safe-regex2')
}
```

[Semantic Versioning](https://semver.org/) describes the dependency hell that many Javascript applications suffer from. I believe it is a best practice to avoid it out of the box where possible

**Comment by delvedor** [comment]
Hello! Thank you for checking out the library!
Both [safe-regex2](https://github.com/fastify/safe-regex2) and [semver-store](https://github.com/delvedor/semver-store) are very lightweight, and are not introducing many sub-dependencies *(only 1)*.
I don't see any strong reason to increase the complexity of this module just to save a few bytes :)
