### ISSUE TITLE
How to use middleware

### ISSUE THREAD

**Issue by m-dary-nur** [delvedor/find-my-way#141]
Hi, can you show example how to use middleware like cors or socket.io with find-my-way router ?
 Thank you

**Comment by delvedor** [comment]
Hello! This is an HTTP router and not a [connect](https://www.npmjs.com/package/connect) like framework :)
This library will only route your requests to a specified handler, if you want to have a full-featured framework I suggest you look at [Fastify](https://fastify.io/).
