### ISSUE TITLE
No match when ignoreTrailingSlash is set to true

### ISSUE THREAD

**Issue by milad-abbasi** [delvedor/find-my-way#145]
## Bug Report
This happens when `ignoreTrailingSlash` option is set to `true`

```js
const router = require("find-my-way")({ ignoreTrailingSlash: true });

router.get('/a/c', () => {});
router.get('/a/:whatever/b', () => {});

router.find('GET', '/a/c/b');
// null
router.find('GET', '/a/AnythingExcept"c"/b');
// {handler: Function, params: {whatever: "AnythingExcept\"c\""}, store: null}
```

## Expected behavior

Path that must match:
`/a/AnythingHere/b`

Path that does not get a match:
`/a/c/b`

## Environment

- *node version*: 12.14.1
- *find-my-way version*: 2.2.1
- *os*: Ubuntu 18.04

**Comment by milad-abbasi** [comment]
@mcollina Any thoughts on this?

**Comment by mcollina** [comment]
This looks like a very bad bug. Would you like to send a PR to fix it?

**Comment by milad-abbasi** [comment]
> This looks like a very bad bug. Would you like to send a PR to fix it?

I'm afraid I don't have the time.
