### ISSUE TITLE
Colliding routes causes params to be undefined in route handler

### ISSUE THREAD

**Issue by ajaco** [delvedor/find-my-way#149]
Hi! 

I was working on a project and I found some odd behaviour while using Fastify. I managed to reproduce it in `find-my-way`, so here goes.

Given the following routes, each with their own handler:

- `GET /foo/:id` (handler 1)
- `GET /foo/:color/:id` (handler 2)
- `GET /foo/red` (handler3)

If you then do a `GET /foo/red/123`, the correct handler (handler 2) will be invoked.
The `id`-param will correctly be `'123'`, but the `color` param is undefined. 

If you do a `GET /foo/blue/123`, both params are correct (`blue`, `123`). 

Handler 3 is still correctly invoked for `GET /foo/red`. So the routing is correct, but the params are wrong. 

If you unregister `GET /foo/red` the `/foo/:color/:id` route will then work again with `red`.
 
I created a fork of the repo with a unit test to illustrate the problem: https://github.com/ajaco/find-my-way/commit/8b489491ed1f87441fc178466382495d8fba3e3d

That test will fail with the following output: 
![image](https://user-images.githubusercontent.com/3799118/81797707-7187e180-950f-11ea-932e-306e174a46ad.png)

So I'm not sure if this is a bug or intended, but I found it very odd. Hopefully this issue will either  highlight a bug, or make me understand this behaviour.

**Comment by Eomm** [comment]
It seems related to https://github.com/fastify/fastify/issues/2261

**Comment by mcollina** [comment]
The solution is to:

```
GET /foo/:id (handler 1)
GET /foo/:color/:id (handler 2) <-- same handler
GET /foo/red (handler3)
GET /foo/red/:id (handler 2) <-- same handler
```

**Comment by ajaco** [comment]
> The solution is to:
> 
> ```
> GET /foo/:id (handler 1)
> GET /foo/:color/:id (handler 2) <-- same handler
> GET /foo/red (handler3)
> GET /foo/red/:id (handler 2) <-- same handler
> ```

This does not solve the problem. 

If you request `GET /foo/red/123`, `req.params` will look like this: `{id: '123'}`. 

So while you, in this specific case, can infer that `color` missing from the `req.params` means that its value is actually `red`, that is not sustainable. What happens if you register the following routes: 

> ```
> GET /foo/:id (handler 1)
> GET /foo/:color/:id (handler 2) <-- same handler
> GET /foo/red (handler3)
> GET /foo/red/:id (handler 2) <-- same handler
> GET /foo/blue/:id (handler 2) <-- same handler
> ```

If someone requests `/foo/red/123` now, how do you know its `red`? It could be blue as well now.

**Comment by mcollina** [comment]
If you are using `fastify`,  you can find the options you have passed in when creating the routes as `req.context.config`.

**Comment by mcollina** [comment]
You can also set a default for the color param with configuring a schema for the params: https://www.fastify.io/docs/latest/Validation-and-Serialization/#validation.

**Comment by bugagashenkj** [comment]
This issue was fixed. I added a test here #262. We can close this.
