### ISSUE TITLE
URL rewriting

### ISSUE THREAD

**Issue by digitalmio** [delvedor/find-my-way#150]
I am wondering is it possible to do some trick and rewrite the URLs, like here for Express via middleware:
https://github.com/kapouer/express-urlrewrite

I am using Fastify and tried to change URL "onRoute", but it is not working as expected...
Many thanks

**Comment by mcollina** [comment]
I think this would be a nice addition, either in here or in Fastify.

In Fastify there is no "preRouting" hook where you can inject said functionality.
I'd be recommending to have a startup option that allows to overwrite `req.url` (node core objects). 

I would keep this module without side effects.

@delvedor wdyt?

**Comment by delvedor** [comment]
I agree that the feature should better live in Fastify. This module is for routing only :)
Unfortunately, it will be impossible to encapsulate the hook, as the encapsulation storage is provided by fin-my-way.

**Comment by digitalmio** [comment]
OK. Shall I close this ticket then and open new one on Fastify as a Feature Proposal?

**Comment by mcollina** [comment]
that'd be perfect, yes!
