### ISSUE TITLE
[Request] Deno Library

### ISSUE THREAD

**Issue by jhechtf** [delvedor/find-my-way#164]
Greetings @delvedor, this is me formally asking if you have plans to make a Deno version of this library; if not, would you mind if I use your library as a base to create a Deno workable library?

**Comment by erfanium** [comment]
I'm working on it here:

**Comment by bugagashenkj** [comment]
I guess we have nothing to do with it. Can we close it?

**Comment by jhechtf** [comment]
Yes, thank you!
