### ISSUE TITLE
Feature discussion: Support for request-based constraints

### ISSUE THREAD

**Issue by AyoubElk** [delvedor/find-my-way#165]
## 1. Overview:

Find-my-way currently supports constraining routes only by versions. 

The following is a proposal, based on the discussion in Fastify's issue [#2498](https://github.com/fastify/fastify/issues/2498), to add support for more generic request-based constraints.

@airhorns already made the case for both the motivation and utility of this feature, so I'll be going over the technical implementation details directly.

### A) Considerations:

To start off, these are some important things that need to be taken into account, as outlined in the issue referenced above:

1. The route should be fully decided by the router
2. The suggested solution shouldn't negatively affect the performance of:
    - Non-constrained routes
    - Version-only constrained route
    - Other constrained routes (to some extent, will detail below what I mean exactly)
3. Eventhough the focus of that issue was host-based constraining, it would be great if there is a generic way for request-based constraining that doesn't affect performance

### B) Analysis of relevant find-my-way concepts:

Currently, find-my-way uses internally a highly performant Radix Tree in order to store and route requests. 

Each node of the tree (that represents a supported path) stores a `handlers` object that maps each supported http method for that path to its handler.

Additionally, versioning routes is allowed by using a default accept-version strategy, *that can be overriden by the user at their own risk*.

This strategy contains two properties:

- `storage` - the factory function for the Storage of the handlers based on their version, it returns an instance of the `semver-store`.
- `deriveVersion` - the function to determine the version based on the request

For versioned routes, a `storage` instance is created for each node and used to map each supported http method for that path to its handler, instead of the `handlers` object used for non-versioned routes.

### C) Solution:

In RoR it is possible to constrain a route based on any method on the request object that returns a string, as detailed [here](https://guides.rubyonrails.org/routing.html#request-based-constraints):

> Request constraints work by calling a method on the [Request object](https://guides.rubyonrails.org/action_controller_overview.html#the-request-object) with the same name as the hash key and then compare the return value with the hash value. Therefore, constraint values should match the corresponding Request object method return type. For example: constraints: { subdomain: 'api' } will match an api subdomain as expected, however using a symbol constraints: { subdomain: :api } will not, because request.subdomain returns 'api' as a String.

This means that the user has the ability to use any combination of constraints, where each one can be:

1. Equal to the corresponding request value
2. A regex that matches to the corresponding request value
3. An [advanced constraint](https://guides.rubyonrails.org/routing.html#advanced-constraints) where the user provides an object that responds to **matches? method** that Rails should use.
    - @mcollina mentioned [here](https://github.com/fastify/fastify/issues/2498#issuecomment-677703974) that this option isn't interesting as a feature, because the route needs to be fully decided by the router itself.

With this as a starting point, my suggested solution to allow support for additional constraints in a generic way is to use at the router level a new `acceptConstraintsStrategy` object instead of the current `acceptVersionStrategy`. 

The object would maintain the same structure:

- `storage` - the factory function for the Storage of the handlers based on their constraints, it returns an instance of a new `ConstraintsStore`; this store can contain child strategies (version, host, etc...) that will each have the same structure (`storage` and `deriveConstraint`).
- `deriveConstraints` -  the function to determine the constraints values based on the request

The `ConstraintsStore` will expose methods `set`, `get`, and `empty`, and will match constraints following this logic:

As an example, let's take these constraints: 

```jsx
{ version: '1.0.x', host: 'auth.airhorns.dev' }
```

- Calling the `set` method with these constraints will result in a call to the `set` method of all the strategies used, in this case `version` and `host`
- Calling the `get` method will result in a call to the `get` method of all the strategies used, in this case `version` and `host`. Since the strategies store handlers independently, if one of them returns `null` then we can know that no match that fulfills all constraints is found and we return `null`, otherwise we return the stored handlers.

Addtionally, given the analysis in the previous section, it's important to note that the use of versioned routes storage is only done if `deriveVersion` returns a non empty value.

This works well for the version constraint, which has to be explicitly set in the `accept-version` header. For other constraints like the header `host`, it will always contain a value which would imply the constrained storage will always be used (Remember that each router tree node currently contains separate non-versioned and versioned storage handlers). 

This raises a few questions that I'd like to open a discussion about:

1. (Somewhat off-topic) In the current code, if the user provides an `accept-version` header with value `*` (which allows matching any version), but no version is specified when registering the route. This would return no handler since the versioned handler storage would be used. Is this by design?

2. Should we support constraints for all request object properties by default, similar to RoR? 
3. If default support is added, how do you propose matching be done? Given the importance of performance for fastify, I'd assume use of regex matching is out of question, that leaves two options as far as I can tell:
    - Exact match
    - Default strategies provided for all request properties
4. How should the router api be updated to use constraints? Have a `constraints` property inside the `opts` parameter when registering the route? Replace the `opts` param with `constraints`? Or do you have a better suggestion?
5. If you agree with my reasoning, what would be the best way to allow the user to provide custom strategies?

**Comment by airhorns** [comment]
Nice work!

> (Somewhat off-topic) In the current code, if the user provides an accept-version header with value * (which allows matching any version), but no version is specified when registering the route. This would return no handler since the versioned handler storage would be used. Is this by design?

Seems like a bug to me, but would be a breaking change, so my suggestion would be to log an issue for this but not try to fix it in this work

> Should we support constraints for all request object properties by default, similar to RoR?

The other two constraints I have used (very rarely) would be protocol (this route is only available on SSL) and header value (this route is only available if this header is set). I don't think those are really that desirable of features, so my suggestion would be to leave the option open but not fully finish constraints other than `host`

> How should the router api be updated to use constraints? Have a constraints property inside the opts parameter when registering the route? Replace the opts param with constraints? Or do you have a better suggestion?

Do you mean the routing API or the route registration API? For the routing API (`.find`), I might suggest changing the API to accept the whole `http.IncomingMessage`, which allows for reading more properties off of it in the future. For the route registration API, I would say your idea of adding a `constraints` key to the `opts` makes sense to me, and that the version should become a constraint.

> If you agree with my reasoning, what would be the best way to allow the user to provide custom strategies?

I am not sure that host based constraints really need pluggable strategies. I think if the router supports string and RegExp based host constraints (with documentation that RegExp is gonna be slower than string) I think that will cover just about every use case. Hostnames aren't really like versions where they might have semantics beyond just the contents of the string (like a semantic version). So I would suggest the data-structure you proposed being sufficient, but then having `find-my-way` always use a built in host matching strategy that we could make pluggable later if really needed. Less changes seems better in this instance.

@mcollina curious to hear what you think!

**Comment by mcollina** [comment]
I'm sorry this is taking so long to respond. Unfortunately it would take me a significant amount of time to respond to all the question and provide some technical direction. We haven't really explored this space, so all direction would be really loose.

The recommendation would be to start working on some code, and we'll be happy to review.
