### ISSUE TITLE
Question: How to route a wildcard path with slashes?

### ISSUE THREAD

**Issue by bobaaaaa** [delvedor/find-my-way#171]
Hey 👋 

How would you model the following URL pattern:

```
/folderA/$ID.html
/folderA/folderB/$ID.html
/folderA/folderB/folderC/$ID.html
/folderA/folderB/folderC/folderD/$ID.html
.... 100 more
```

I only need the `ID`. Everything before that I don't care.

```ts
// Using fastify here.
// I would expect something like this:
server.get(`/:folders(.*)/:id.html`, async request => {
  console.log('Params', request.params);
  return 'success\n';
});
```

Or do I need to add each folder path to a route pattern? Like this:

```ts
server.get(['/:folderA/:id.html', '/:folderA/:folderB/:id.html', '/:folderA/:folderB/:folderC/:id.html'], async request => {
  console.log('Params', request.params);
  return 'success\n';
});
```

Thx for the help ❤️

**Comment by delvedor** [comment]
Hello! I would avoid using regular expressions, as those will slow down your performance quite a bit.
If you have a very big number of nested folders that does not allow you to create specific routes for each one of them, probably the easiest thing to do is the following:
```js
fastify.get('/*', async (req, reply) => {
  const folders = req.url.split('/')
  const file = folders.pop()
  console.log(folders, file)
})
```
Otherwise, you can [glob](https://www.npmjs.com/package/glob) the directory that contains all of your folders, and then create a static route for each one of them, which is similar to what [fastify-static](https://github.com/fastify/fastify-static) is doing.

**Comment by bobaaaaa** [comment]
@delvedor Thx for help 👍

**Comment by murarustefaan** [comment]
Hey @delvedor, sorry for the tag bug I could not find this anywhere else and it is related to this issue, please correct me if I am wrong.

I'm using Fastify to map paths to Github repositories, with some actions included in the URL. 
Let's say I have an endpoint that looks like
`/lookup/delvedor/find-my-way/:ref/download`.
Here the ref can also include forward-slashes (eg. for feature, bugfix, chore branch names etc., feat/test-feature). Is there a way to use regular expressions (or possibly else that I am missing) to map this sort of behaviour?
I noticed that Express5-beta added this sort of behaviour usiong param modifiers that in my case would look like `:ref+`.

I am at least willing to give Regular Expressions a try as this endpoint is not a high-rps one.

**Comment by ivan-tymoshenko** [comment]
@murarustefaan Hi, the wildcard param is the only param that can get some information through the slashes. Params that start with a colon are looking for data only between two slashes. This is design related restriction for the find-my-way.

When the client side sends you a path param it should encode it with a [encodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) in the same way as it should encode query params.

**Comment by murarustefaan** [comment]
Hey @ivan-tymoshenko, this is what I was already doing, yet I wanted to implement it somehow like Github is already doing this, with having all of this information directly in the path, not encoded. 

It's probably an overhead as adding a wildcard would require parsing of the url itself and is probably not worth considering right now.

Nevertheless, thank you for your quick response. 👍🏽
