### ISSUE TITLE
Migrate to Fastify org

### ISSUE THREAD

**Issue by jsumners** [delvedor/find-my-way#173]
I realize we had a conversation about this somewhere at some point, but I can't remember when or where. I was just trying to answer https://github.com/fastify/fastify/issues/2738 and went to the Fastify GitHub org to find the `find-my-way` repo. It wasn't there. Given this is such a core piece of Fastify, I think it should be within that org.

**Comment by mcollina** [comment]
I tend to agree.

**Comment by Eomm** [comment]
I think you are referring to https://github.com/fastify/avvio/issues/109

While I agree on `avvio`, since `fastify` is the main user (only) of that module it has 12 dependents; this is not the case of `find-my-may` that it is framework agnostic and has more main users dependents.

I'm not contrary of course, it is a delvedor's choice in my opinion 👍

**Comment by jsumners** [comment]
Yeah, that was it. Good find @Eomm. My last comment still stands https://github.com/fastify/avvio/issues/109#issuecomment-625904767

**Comment by airhorns** [comment]
I would be in favour of this move too

**Comment by airhorns** [comment]
@delvedor ping -- thoughts?

**Comment by jsumners** [comment]
https://github.com/fastify/fastify/issues/3663

**Comment by bugagashenkj** [comment]
@delvedor @mcollina What about this issue. Should we move find-my-way to the Fistify org, or should we close this issue?

**Comment by jsumners** [comment]
https://github.com/fastify/fastify-http-proxy/issues/265#issuecomment-1216126120

> @mcollina sure, I can try, do you know where fastify has the route-matching implemented?

**Comment by jsumners** [comment]
https://github.com/fastify/fastify/issues/4506 that we can't move here because it isn't in the org.
