### ISSUE TITLE
Allow routes with colons

### ISSUE THREAD

**Issue by morigs** [delvedor/find-my-way#175]
Currently there is no way to define a route with colon in the path (expect regular expressions of course)
Some companies require following the [Google API conventions](https://cloud.google.com/apis/design/custom_methods) which use colon
It seems Express.js allows that by [using doubled colon](https://stackoverflow.com/a/52692196) or by [wrapping colon in the brackets](https://github.com/expressjs/express/issues/3857#issuecomment-589792737)
I believe Fastify should also have a way to achieve this behavior

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
