### ISSUE TITLE
Question: Content Negotiation RFC 2616 Compliance

### ISSUE THREAD

**Issue by matthyk** [delvedor/find-my-way#181]
I am currently developing a new strategy for content negotiation. To develop the strategy `RFC 2616` compliant it is required to send back a `406` error code (section `14.1`), if the server cannot send an acceptable response. In my understanding this is not possible with the current implementation. Should RFC compliance be ignored or should the current implementation be updated?

**Comment by mcollina** [comment]
Can you please articulate what are your requirements? Fastify (which uses this module) supports content-negotiation on top of this module.

In other terms, this is router, not an HTTP/1.1 server.

**Comment by matthyk** [comment]
Sorry for getting some things mixed up. What I mean, is that the constraints handling happens in the router, which it fine because it is its responsibility to select and call the correct handler. However, the used `lookup` method of the router does not offer any possibilities to define the behaviour if the internally used `find` method returns null, which means that no matching handler is found. Currently the default handler will be called, if no other handler matches. It would be nice to have the possibility to get more information why no route was found, e.g when using a content negotiation constraint, that no acceptable response format is available. This information could be passed to the default handler and the user of the framework (e.g. fastify) can process it.

**Comment by mcollina** [comment]
That's currently not possible... maybe @airhorns has some ideas.

**Comment by airhorns** [comment]
I see the trickiness here, but, I think that this is a pretty special need that doesn't seem like it would generalize that well to the other constraints. What do you think about just documenting that if a developer wants compliance with this RFC, they should make the default handler serve the 406 error code?

**Comment by mcollina** [comment]
I agree

**Comment by matthyk** [comment]
I agree that this is a very specific requirement, but unfortunately the idea of returning `406` in the default handler does not solve the problem, because it is also necessary to return a `415` error code if the format of the entity sent is not supported by the server to follow the RFC specification. 
I will find another solution, thanks for the answer.
