### ISSUE TITLE
[Question] What does this line mean?

### ISSUE THREAD

**Issue by erfanium** [delvedor/find-my-way#186]
While I was creating a Deno port of this project, I saw this line:
https://github.com/delvedor/find-my-way/blob/df6951b650cd9c8cc5cda5c6193951960b994515/node.js#L29

What's the point of  `false || ...`? The first condition is always false!

**Comment by mcollina** [comment]
It sets thee default value to false.

**Comment by erfanium** [comment]
It should be `this.hasConstraints = options.hasConstraints || false` to set the default value to false. `this.hasConstraints = false || options.hasConstraints` is no different from `this.hasConstraints = options.hasConstraints`. I'll create a PR for this

**Comment by erfanium** [comment]
![unknown](https://user-images.githubusercontent.com/47688578/115110867-b4a9ca80-9f92-11eb-859b-881c90e651d5.png)

**Comment by mcollina** [comment]
thanks!
