### ISSUE TITLE
ignoreTrailingSlash right after parametric route not working properly

### ISSUE THREAD

**Issue by MarcelloTheArcane** [delvedor/find-my-way#191]
### Setup

```
const router = require('find-my-way')({
  ignoreTrailingSlash: true
})

router.on('GET', '/:param/*', (req, res, params) => {
  //...
}))
```

I'm using Fastify, so it's a bit different, but that's the gist of it.

### Tests

Path: `/param/blah-blah/`
Matched: ✔️

Path: `/param/blah-blah/more-stuff/`
Matched: ✔️

Path: `/param/`
Matched: ✔️

Path: `/param`
Matched: ❌

### Issue

I'd expect that with `ignoreTrailingSlash` set true, the last one would match as well (since `/param/` does).

**Comment by mcollina** [comment]
I think this is working as expected.

`/:param/*` and `/:param`

Considering them the same route seems overly dangerous.

**Comment by MarcelloTheArcane** [comment]
Okay, that's fine.  I guess in my case I can set up a 302 from `/param` to `/param/`.

It just seemed weird that when I was explicitly setting ignoreTrailingSlash it should let me accept any danger from making them the same.

**Comment by MarcelloTheArcane** [comment]
@mcollina Having done that, I'm now facing another problem I didn't think I should have:

```js
fastify.get('/some-static-url', /* stuff here */)

fastify.get('/:param', (request, reply) => reply.redirect(301, request.params.param))
```

In this scenario, everything is getting caught by that `/:param` redirect, including static URLs (so they then go to `/some-static-url/`).  I thought this shouldn't happen because according to the docs:

> To register a parametric path, use the colon before the parameter name. For wildcard use the star. **Remember that static routes are always inserted before parametric and wildcard.**

**Comment by mcollina** [comment]
That's a different problem than this one, open a fresh issue with a repro.
