### ISSUE TITLE
Route with a . (period) between parameters

### ISSUE THREAD

**Issue by kissmygritts** [delvedor/find-my-way#192]
I've looked over the tests here: https://github.com/delvedor/find-my-way/blob/master/test/issue-17.test.js and I they all seem to check that parameters are successfully parsed when separated for a hyphen. 

Is there a solution for a route like this? `/features/:table/:id.:format` I get the following for the parameters:

```js
{
    "table": "table",
    "id.:format": "1.geojson"
}
```

**Comment by mcollina** [comment]
Ouch! I don't think this is supported, would you like to send a PR?

**Comment by kissmygritts** [comment]
I'll see what I can do, but I can't make any promises. 

I did find a work around. In my case the id will always be a number so the following works: 
`/features/:table/:id(\\d+).:format`

```
{
    "table": "table",
    "id": 1,
    "format": "geojson"
}
```

Thanks for the quick reply.
