### ISSUE TITLE
Parametric path resolution

### ISSUE THREAD

**Issue by deividasjackus** [delvedor/find-my-way#20]
```js
const http = require("http");
const router = require("find-my-way")();

router.on("GET", "/a/:param", (req, res, params) => res.end(JSON.stringify(params)));

http.createServer(router.lookup.bind(router)).listen(3000);
```

### Works as expected
http://localhost:3000/a/perfectly-fine-route => `{"param":"perfectly-fine-route"}`

### Does not work
- http://localhost:3000/a => `{"param":"a"}`
- http://localhost:3000/a-non-existing-route => `{"param":"a-non-existing-route"}`
- http://localhost:3000/a/ => `TypeError: Cannot read property 'length' of null`

**Comment by delvedor** [comment]
I'm able to reproduce this, thank you for reporting!
I'll fix it as soon as I can.

If you want to try, fire a PR! :)

**Comment by mlovrovich** [comment]
```js
    const http = require('http')
    const router = require('find-my-way')()

    router.on('GET', '/:namespace/:type/:id', (req, res, params) => {
        res.end('{"message":"hello world"}')
    })

    router.on('POST', '/:namespace/jobs/:name/run', (req, res, params) => {
        res.end('{"message":"hello world"}')
    })

    const server = http.createServer((req, res) => {
        router.lookup(req, res)
    })

    server.listen(4000, err => {
        if (err) throw err
        console.log('Server listening on: http://localhost:4000')
    })
```

### Works as expected
GET http://localhost:4000/test_namespace/test_type/test_id
GET http://localhost:4000/test_namespace/jobss/test_id

### Does not work
GET http://localhost:4000/test_namespace/jobs/test_id
