### ISSUE TITLE
Incorrect wildcard behavior

### ISSUE THREAD

**Issue by delvedor** [delvedor/find-my-way#202]
If a route contains a wildcard and a static path at the end, it will find a route even if the last chunk of the path does not match.

```js
const router = require('find-my-way')()

router.get('/*/foo', (req, res) => {})

console.log(router.find('GET', '/')) // should be null, it finds the route instead.
```

**Comment by RafaelGSS** [comment]
Hi @delvedor I've been working on a solution for it, however, I feel that would be great an advice on it.

As far I understood from the source code, when we register: 

```js
router.get('/*/foo', (req, res) => {})
```

it generate the following node:

```sh
Node {
<   prefix: '/',
<   label: '/',
<   method: 'GET',
<   handlers: [],
<   unconstrainedHandler: null,
<   children: {
<     '*': Node {
<       prefix: '*/foo',
<       label: '*',
<       method: 'GET',
<       handlers: [Array],
<       unconstrainedHandler: [Object],
<       children: {},
<       numberOfChildren: 0,
<       kind: 2,
<       regex: null,
<       wildcardChild: null,
<       parametricBrother: null,
<       constrainer: [Constrainer],
<       hasConstraints: false,
<       constrainedHandlerStores: null,
<       _getHandlerMatchingConstraints: [Function: compileThenGetHandlerMatchingConstraints]
<     }
<   },
<   numberOfChildren: 1,
<   kind: 0,
<   regex: null,
<   wildcardChild: Node {
<     prefix: '*/foo',
<     label: '*',
<     method: 'GET',
<     handlers: [ [Object] ],
<     unconstrainedHandler: {
<       handler: [Function (anonymous)],
<       params: [Array],
<       constraints: {},
<       store: null,
<       paramsLength: 1
<     },
<     children: {},
<     numberOfChildren: 0,
<     kind: 2,
<     regex: null,
<     wildcardChild: null,
<     parametricBrother: null,
<     constrainer: Constrainer { strategies: [Object], strategiesInUse: Set(0) {} },
<     hasConstraints: false,
<     constrainedHandlerStores: null,
<     _getHandlerMatchingConstraints: [Function: compileThenGetHandlerMatchingConstraints]
<   },
<   parametricBrother: null,
<   constrainer: Constrainer {
<     strategies: { version: [Object], host: [Object] },
<     strategiesInUse: Set(0) {}
<   },
<   hasConstraints: false,
<   constrainedHandlerStores: null
< }
```

---

Some solutions that come to my mind at the first moment:

1. Change https://github.com/delvedor/find-my-way/blob/master/index.js#L204 to 

```diff
+      if (i === len - 1) {
        // add the wildcard parameter
        params.push('*')
        return this._insert(method, path.slice(0, len), NODE_TYPES.MATCH_ALL, params, handler, store, null, constraints)
+      } else {
+     // TODO: change the insertion method to a new type (NODE_TYPES.MATCH_ALL_WITH_STATIC_PREFIX
+     }
```

2. Change https://github.com/delvedor/find-my-way/blob/master/node.js#L159 to match the static path somehow.

How do you solve it?

**Comment by RafaelGSS** [comment]
Yes. I'm not sure whether I'll have free time this week or further weeks to look at it, but assuming that it will modify a hot path (find) we should be careful in that change. I'd be glad to review a PR if you make it.

**Comment by bugagashenkj** [comment]
I would say that we can't implement it and we don't need it. The real difference between parametric and wildcard param is that wildcard parma can have slashes, but parametric doesn't. If we allow having something in a path after wildcard param, it would be impossible to handle it.

Examples: `/*/:param`, `/*/*` (+ you can add any static parts inside them, it doesn't help)

If you need a param inside a URL that contains slashes I would say you need to present encode this param and use regular parametric param.
