### ISSUE TITLE
Regex tokens not working

### ISSUE THREAD

**Issue by zekth** [delvedor/find-my-way#204]
These two tokens does not seem to work:

```js
test('route with an extension regex 2', t => {
  t.plan(2)
  const findMyWay = FindMyWay({
    defaultRoute: (req) => {
      t.fail(`route not matched: ${req.url}`)
    }
  })
  findMyWay.on('GET', '/test/S/:file(^\\S+).png', () => {
    t.ok('regex match')
  })
  findMyWay.on('GET', '/test/D/:file(^\\D+).png', () => {
    t.ok('regex match')
  })
  findMyWay.lookup({ method: 'GET', url: '/test/S/foo.png', headers: {} }, null)
  findMyWay.lookup({ method: 'GET', url: '/test/D/foo.png', headers: {} }, null)
})
```

Ref:
- S : non whitespace character
- D : non digit character

Any clue why those does not work? Even with the `allowUnsafeRegex` is does not work.

**Comment by mcollina** [comment]
At first glance I would not use the ^ there.

(I would usually recommend against using regexps for these).

**Comment by mcollina** [comment]
I don't know, this would probably be investigated. Maybe it's an escaping issue? Or we should pass some custom option when we create the Regexp?

**Comment by zekth** [comment]
I wanted to know if a known flaw. I'll dig it.

**Comment by jtarchie** [comment]
The capture group for both includes  `^`, which in this context means _"asserts position at start of line"_. These aren't ever going to match because there is no start of line here.

**Comment by zekth** [comment]
> The capture group for both includes `^`, which in this context means _"asserts position at start of line"_. These aren't ever going to match because there is no start of line here.

I'm not sure this is the case. As this test for example won't pass either:
https://github.com/delvedor/find-my-way/blob/70844a9c1effe065915ceabef3867abb1add618d/test/regex.test.js#L37-L50

**Comment by jtarchie** [comment]
It’s still looking for the start of line. What do you think the caret is suppose to be doing here?

**Comment by zekth** [comment]
In this context
```js
  findMyWay.on('GET', '/test/:id(^\\d+$)/hello', () => {
    t.ok('regex match')
  })

  findMyWay.lookup({ method: 'GET', url: '/test/12/hello', headers: {} }, null)
```
The line passed to the regex test is `12` so it matches. Which is executed here: https://github.com/delvedor/find-my-way/blob/70844a9c1effe065915ceabef3867abb1add618d/index.js#L552

This case works, so i don't get your point.

Even without `^` token, the test for `\S` and `\D` doesn't passe

But if you have a solution for this, raise a PR or a working example

**Comment by bugagashenkj** [comment]
@mcollina @delvedor This can be closed.
