### ISSUE TITLE
Can this be simplified to use with websockets?

### ISSUE THREAD

**Issue by tamilvendhank-helptap** [delvedor/find-my-way#205]
Hello there,

I am wondering, if this library can be simplified to create an another library, for websocket messages routing.
If it can do something like following, it would be great!

```

const router = new Router();
router.on('/users/:userId/posts', handler);

function handler(urlParams, payload) {
   console.log(urlParams, payload); // {userId: 12345} {...}
}

websocketServer.on('connection', function connectionHandler(connection) {

  connection.on('message', function messageHandler(message) {

    const messageObject = validateMessageFormat(message);
    // messageObject = { url: '/users/12345/posts', payload: {...} };
    router.lookup(messageObject);     

  });  

});

```

**Comment by mcollina** [comment]
I think you could create such a small wrapper.

**Comment by bugagashenkj** [comment]
I agree that it's shouldn't be here. Can we close it?

**Comment by tamilvendhank-helptap** [comment]
@mcollina, @ivan-tymoshenko apologies. I must have closed this on my own. 
@mcollina, I took your suggestion and wrote the code. I have been using it on production for a while. Thanks for that.
