### ISSUE TITLE
Decoding URL Components

### ISSUE THREAD

**Issue by ivan-tymoshenko** [delvedor/find-my-way#234]
There is how decoding URL components is working right now. If URL contains "%" symbol - URL will be decoded by standard js decodeURI function and if URL contains one of this symbols "# $ & + , / : ; = ? @", URL params will be parsed from the original (non-decoded) url and will be decoded either by fastDecode or customDecode function. There is a problem here. If one part of a URL has one of this symbols "# $ & + , / : ; = ? @", all url params will be parsed by fastDecode function and not parsed with decodeURI function. 

```js
test('Decode url components', t => {
  t.plan(3)

  const findMyWay = FindMyWay()

  findMyWay.on('GET', '/:param1/:param2', () => {})

  t.same(findMyWay.find('GET', '/foo%23bar/foo%23bar').params, { param1: 'foo#bar', param2: 'foo#bar' })
  t.same(findMyWay.find('GET', '/%F0%9F%8D%8C/%F0%9F%8D%8C').params, { param1: '🍌', param2: '🍌' })
  t.same(findMyWay.find('GET', '/%F0%9F%8D%8C/foo%23bar'), null) // shouldn't be true
  // t.same(findMyWay.find('GET', '/%F0%9F%8D%8C/foo%23bar'), { param1: '🍌', param2: 'foo#bar' }) // should be true
})
```

**Comment by bugagashenkj** [comment]
I'm pretty sure that the previous test should work how I described it. But here I have a problem. Which of the two last commented test cases should be correct.

```js
test('Decode url components', t => {
  t.plan(4)

  const findMyWay = FindMyWay()

  findMyWay.on('GET', '/:param', () => {})

  t.same(findMyWay.find('GET', '/foo%23bar').params, { param: 'foo#bar' })
  t.same(findMyWay.find('GET', '/%F0%9F%8D%8C').params, { param: '🍌' })
  t.same(findMyWay.find('GET', '/%F0%9F%8D%8C-foo').params, { param: '🍌-foo' })
  t.same(findMyWay.find('GET', '/%F0%9F%8D%8C-foo%23bar').params, { param: '🍌' }) // IMHO, it's wrong
  // t.same(findMyWay.find('GET', '/%F0%9F%8D%8C-foo%23bar').params, { param: '🍌-foo#bar' }) // First option
  // t.same(findMyWay.find('GET', '/%F0%9F%8D%8C-foo%23bar').params, { param: '%F0%9F%8D%8C-foo#bar' }) // Second option
})
```

**Comment by bugagashenkj** [comment]
Another way of this problem: when people create a custom decoder what url they expect? If we pass to the decoder completely raw URL as we do know, then in one case if it's just '/%F0%9F%8D%8C' they will receive '🍌', but if it's '/%F0%9F%8D%8C' + something that contains "# $ & + , / : ; = ? @", they will receive "/%F0%9F%8D%8C" + something. And they will have to parse not only this symbols "# $ & + , / : ; = ? @", but also banana.

**Comment by bugagashenkj** [comment]
There is a test that I don't understand.
1. There defined a custom decoder.
2. There is a dynamic route 
https://github.com/delvedor/find-my-way/blob/5beaacfcb6d1bb53663a90b5e7f0d5e9540e15ce/test/custom-decode-uri.test.js#L56
3. We pass "/%23%F0%9F%8D%8C" (encoded /#🍌 as I understand)
https://github.com/delvedor/find-my-way/blob/5beaacfcb6d1bb53663a90b5e7f0d5e9540e15ce/test/custom-decode-uri.test.js#L66
4. We expected "/%23%F" as a result
https://github.com/delvedor/find-my-way/blob/5beaacfcb6d1bb53663a90b5e7f0d5e9540e15ce/test/custom-decode-uri.test.js#L41

The last part is simply ignored.

**Comment by Eomm** [comment]
> If URL contains "%" symbol - URL will be decoded by standard js decodeURI function 

True

>  if URL contains one of this symbols "# $ & + , / : ; = ? @"

Almost: the URL must contain those _encoded_ symbols

>  If one part of a URL has one of this symbols "# $ & + , / : ; = ? @", all url params will be parsed by fastDecode function and not parsed with decodeURI function

Do you think fastDecode has some issues?

> t.same(findMyWay.find('GET', '/%F0%9F%8D%8C-foo%23bar').params, { param: '🍌' }) // IMHO, it's wrong

I agree

> Which of the two last commented test cases should be correct.

I think the first one: `'🍌-foo#bar'`

> We expected "/%23%F" as a result

I agree that it is an error. There is some issue with the parameter counter when the slice function is applied.

```
{
  originPath: '/%23%F0%9F%8D%8C',
  decoded: '/%23🍌',
  containsEncodedComponents: true
}
```

**Comment by bugagashenkj** [comment]
The problem: if we pass to the fastDecode/customDecode non-decoded (by the decodeURI function) param, we need to parse 🍌 manually; if we pass decoded param, we will decode it twice and will get a wrong param value.

**Comment by bugagashenkj** [comment]
I have a problem here and I need your help with it. I will describe how we decode a URL with params. At first, we decode the whole URL with decodeURI function, in order to decode symbols we need to match the URL to a registered path. Then if we find a param, we need to parse and decode it again from the original path (from the path that we didn't decode with decodeURI). We found the param in the decoded path and should parse it from the non-decoded path, and these paths could mismatch.

Example:
1. We set up  `/🍌/:param` URL
2. Trying to match this URL `/%F0%9F%8D%8C/param%23` (encoded 🍌 symbol == %F0%9F%8D%8C). We expect that '%F0%9F%8D%8C' would be decoded to the 🍌, then we will find a param and will decode it. Param should be equal 'param#'
3. We parse the URL with decodeURI function and get `/🍌/param%23` URL
4. We find a param in the decoded URL `/🍌/param%23`, it starts at index 3
5. We need to parse and decode param from the original URL `/%F0%9F%8D%8C/param%23`, but all we know is that param starts at index 3 in the decoded URI.

Any good ideas of how should we do that?

**Comment by bugagashenkj** [comment]
@mcollina @Eomm I need your help here. Maybe you know a good example of another lib or standard which should describe how it should work?

**Comment by mcollina** [comment]
I would recommend looking at path-to-regexp or URLPatter https://wicg.github.io/urlpattern/

**Comment by bugagashenkj** [comment]
@mcollina I tested the path-to-regexp library.
```js
const { match } = require("path-to-regexp")

const matchStatic = match("/🍌", { decode: decodeURIComponent });
console.log(matchStatic("/%F0%9F%8D%8C")) // returns false

console.log(decodeURI('/%F0%9F%8D%8C')) // returns "/🍌"
```

Is this correct behavior?

**Comment by bugagashenkj** [comment]
URLPattern matches the url, but it doesn't decode the param.
```js
const pattern = new URLPattern('https://host.com/🍌:id')
console.log(pattern.exec('https://host.com/%F0%9F%8D%8C/123%23')) // returns param id as 123%23, not as 123# 
```

**Comment by bugagashenkj** [comment]
path-to-regexp, URLPattern, and find-my-way have three different ways to deal with encoded URLs.

**Comment by mcollina** [comment]
I don't think there is a preferred way to handle this.

**Comment by bugagashenkj** [comment]
Ok, but the problem is that find-my-way has an issue with that.
https://github.com/delvedor/find-my-way/issues/234#issuecomment-1100897675

**Comment by mcollina** [comment]
Unfortunately I do not have enough time right now to design a solution for this. I'd be happy to review a PR.

IMHO we should align to either path-to-regexp or URLPattern.
