### ISSUE TITLE
Issue in parameter resolution

### ISSUE THREAD

**Issue by fxalgrain** [delvedor/find-my-way#235]
Hi, 

I m using my find-my-way via Fastify and I m facing an issue parametrics url. 

I defined a route like that : `GET /images/:id.jpg`
When I make this request `GET /images/123456.jpg` it works as expected but when I make this one :  `GET /images/12346-fr.jpg`
It's does not work.

I think the issue is linked  to the support of multi params

**Comment by bugagashenkj** [comment]
Hi, IMHO, it shouldn't be a multiparametric node since there is only one param in your URL.

**Comment by bugagashenkj** [comment]
I think the problem should be where it defines it as a multiparametric route.
https://github.com/delvedor/find-my-way/blob/5beaacfcb6d1bb53663a90b5e7f0d5e9540e15ce/index.js#L202

**Comment by fxalgrain** [comment]
Yes it sounds a bit strange. As I understand the . is defined as a splitter. 
Made a change looks me risky.

**Comment by fxalgrain** [comment]
I think if we change this behavior , the .jpg will not be excluded from param value
