### ISSUE TITLE
Meta issue

### ISSUE THREAD

**Issue by ivan-tymoshenko** [delvedor/find-my-way#252]
@mcollina Hi, I can go through the issues that we have and describe where we can do something and where we can't. Can we close some of them after that? I know there are only 20 of them, but it would be great to add at least bug or enhancement labels for them.

**Comment by Eomm** [comment]
Issues triage is welcome!

**Comment by bugagashenkj** [comment]
Issues that were fixed and should be closed: #190, #161, #149, #101
Suggestions that we shouldn't implement (IMHO), can be closed: #205, #202, #164

**Comment by ivan-tymoshenko** [comment]
@mcollina thank you very much.
