### ISSUE TITLE
Pretty print method with a common prefix option doesn't have much sense

### ISSUE THREAD

**Issue by ivan-tymoshenko** [delvedor/find-my-way#271]
There is an option in the prettyPrint method that as said "prints the representation of the internal radix tree, useful for debugging". The internal structure has a tree for each HTTP method, but the pretty print method builds one merged tree. To build this tree, it is modifying node prefixes, so it's will not help you if you want to debug something.

Another problem is that this method doesn't print the tree, it rebuilds it. This means that we have to maintain the same rules in two places.

I want to leave prettyPrint method with commonPrefix = true option. It also rebuilds a tree instead of printing, but it is useful when you need to see all your routes together. And I want to add a method that would print a tree by HTTP method. It will really represent an internal structure and would be helpful for debugging.

**Comment by mcollina** [comment]
go for it!

**Comment by climba03003** [comment]
`commonPrefix: true` print the actual radix tree.
`commonPrefix: false` print the routing tree, it is useful for visualize all the routes (divide by slash).

I would say that the `false` option is added because the `radix-tree` structure is not good for reading (not for debugging).

**Comment by ivan-tymoshenko** [comment]
I don't want to change the behavior of `commonPrefix: false`. I'm more concerned about `commonPrefix: true`. @climba03003 what do you mean by "actual" rooted tree, given that we are building different trees for each HTTP method, but drawing one tree?

**Comment by climba03003** [comment]
> What do you mean by "actual" rooted tree, given that we are building different trees for each HTTP method, but drawing one tree?

Yes. A single `radix` tree to show all `HTTP method` at a same time.
It would be great to show without modifying the `node`.

If I am not mistaken now, this issue contain two point.
1. Keep the current behavior, but it should not modify the `node` for printing.
2. Allow to print with separate `HTTP methods`.

**Comment by ivan-tymoshenko** [comment]
If we print a merged radix tree without changing the nodes, it would be really messy. Why does someone need to print a tree with `commonPrefix: true` option. IMHO to see the internal structure for debugging purposes. In this case, the clearest way to do it is to print the actual radix tree by HTTP method. Can you give an example of when someone needs to print a merged radix tree?

**Comment by climba03003** [comment]
> If we print a merged radix tree without changing the nodes, it would be really messy. Why does someone need to print a tree with `commonPrefix: true` option. IMHO to see the internal structure for debugging purposes. In this case, the clearest way to do it is to print the actual radix tree by HTTP method. Can you give an example of when someone needs to print a merged radix tree?

Not a use-case, but it is not convenient to scan through with multiple tree.
When I need to check for a single `path`, I need to scroll up and down if it is a separate tree.

**Comment by ivan-tymoshenko** [comment]
What if instead of the common prefix we add the method option. If the method option is provided it will print the radix tree for this method, if not it will print the merged routing tree.

**Comment by climba03003** [comment]
> What if instead of the common prefix we add the method option.

It is better.
