### ISSUE TITLE
Wait for async handler to resolve

### ISSUE THREAD

**Issue by alii** [delvedor/find-my-way#274]
Would it be possible to wait for the async handler to resolve in the following code? How could we know when the lookup is done

```ts
fmw.on('GET', '/', async (req, res, params) => {
    // Slow handler that could take some time
});

const data = await before(req, res);

// `await` awaits the async handler
await fmw.lookup(req, res);

await after(data);
```

**Comment by ivan-tymoshenko** [comment]
Hi, the lookup function returns the result of a handler. If you return a promise in your handler, it will return from the lookup function. So yes, it will work.

**Comment by alii** [comment]
ahh okay, perhaps the types are incorrect in this case as it's typed to return `void`:
<img width="963" alt="image" src="https://user-images.githubusercontent.com/25351731/167299476-7eb3fe71-6b8e-415d-8bf9-0feb2df06842.png">

**Comment by ivan-tymoshenko** [comment]
Yes, there should be `any` type. https://github.com/delvedor/find-my-way/blob/a59117d0daf351429919d586e5edea4ef6d2a14b/index.d.ts#L151

Would you like to send a PR to address this issue?

**Comment by alii** [comment]
I can do that, but I think it actually is the correct typings after testing it:

<img width="800" alt="image" src="https://user-images.githubusercontent.com/25351731/167299844-6e5a2a76-9614-49f7-aa41-70569067499b.png">

Also perhaps it would be better to allow a generic with a default value rather than `any`?

**Comment by ivan-tymoshenko** [comment]
The `lookup` returns a handler's result. You can return a value of any type from the handler. I'm not sure that I got your idea of generic type.

https://github.com/delvedor/find-my-way/blob/a59117d0daf351429919d586e5edea4ef6d2a14b/index.js#L319

**Comment by ivan-tymoshenko** [comment]
> I can do that, but I think it actually is the correct typings after testing it:
> 
> <img alt="image" width="800" src="https://user-images.githubusercontent.com/25351731/167299844-6e5a2a76-9614-49f7-aa41-70569067499b.png">
> 
> Also perhaps it would be better to allow a generic with a default value rather than `any`?

Are you sure that your handler returns a promise and not just undefined?

**Comment by alii** [comment]
Ahh forgive me, I had visited a 404 route that was returning `void`. My mistake!

With regards to the generic, I mean to type `lookup` as follows:

```ts
lookup<Context, Response = any>(
      req: Req<V>,
      res: Res<V>,
      ctx?: Context
): Response;
```

**Comment by ivan-tymoshenko** [comment]
Is there any difference between defining a type variable and using it once and inlining it?

**Comment by alii** [comment]
I'm sorry I not sure I understand what you mean by that. I don't really think we need a generic for `Context` here as it is not really used, but Response is so it would make sense to keep that there

**Comment by ivan-tymoshenko** [comment]
Can you give me an example of using a generic Response? Please make sure that the lookup function can return the result of any handler.

**Comment by alii** [comment]
For sure! In my use case all of my handlers return a consistent shape of 

```ts
export type HandlerResult = 
	| {success: true; data: unknown}
	| {success: false; data: {status: number; message: string}};
```

it would be great for me to type something as follows: [https://www.typescriptlang.org/play](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wBYxmOAzKCEOAcgDsIATAUwC4scSBuAKBYGMAbNdAMQFkA6nADeLOBLicIEANYBXMAB4ASnAC8KMgE8AfAAoo1AI61M2MADoAkmXZFgZAOb9qqVMifUANHCOozBisAZWooADcwlTdIMlQfOHYYAA8AfjN5MlkKAHcyAEozNTFJUrgAenLxSQBfFjqOCDj4PBAcjTgyanaBQX181hYaLmQjRKbUeCNTcxwbOwdnV3dPalZh7jH7Zr83QItLUIiomIm1tm3J3dR5ThgARg7WnMtpOUVDE19-XxFUIjocAARNsYNRkjAgTUBixKqUAHqpC4TKZuW4wABMTzarxkCmUIjgN3Y7DcATgMCg8gSlGQMGQGSyuTIcBqBmm3zcv3+IEBIKaYIhUJhcMkiJYQA)

Right now I am doing this:
<img width="760" alt="image" src="https://user-images.githubusercontent.com/25351731/167301721-a59d1b0d-cca3-4330-89d6-9fdb79d35bf8.png">

**Comment by ivan-tymoshenko** [comment]
I'm not sure that this is a good idea. The lookup function isn't generic by itself. And to be generic you have to provide the defaultRoute with the same result type. Otherwise the lookup function will return undefined.

**Comment by ivan-tymoshenko** [comment]
@mcollina What do you think?

**Comment by alii** [comment]
That's fair, in my instance I am sure that all routes will return a `HandlerResult`. I suppose if the results varied then you wouldn't have to provide a generic at all (e.g. defaulting to `any`).

The reason I removed `Context` is simply because it was only used to type `ctx`, which has the same effect as just doing `ctx: unknown` because we don't use `Context` anywhere else.

Happy to hear thoughts :) :heart:

**Comment by ivan-tymoshenko** [comment]
I agree with you, but technically, as I understand, removing Context can break someone's typescript code.
