### ISSUE TITLE
Better handling of wildcard routes

### ISSUE THREAD

**Issue by delvedor** [delvedor/find-my-way#28]
Currently we are suffering the following issue:
Given this route declaration
```js
router.on('GET', '/test/*', () => {})
```
It will respond only to `/test/at-lest.one.character`, while `/test/` will not work.
Is not that easy to solve at the moment, it will require a refactor on how we are handling the routes prefixes, because currently a prefix almost always contains the `/` at the end, and that is our issue.

I'll leave this here, as soon I have enough time I'll get into it.
If someone wants to help, please fire a pr!

Related: https://github.com/fastify/fastify/pull/266

**Comment by BigMurry** [comment]
I have another problem, give the route declaration:
```
router.on('GET', '/test/foo', () => {})
router.on('OPTIONS', '/*', () => {})
```
when the request is `OPTIONS /test/foo`, it will respond `404`

**Comment by delvedor** [comment]
@BigMurry thanks for checking out!
Yes, the problem is related to the prefix handling, indeed the request is `OPTIONS /example/hello` it will work.

**Comment by delvedor** [comment]
@BigMurry while working on this issue I've fixed your issue, I'll publish the fix as soon as I find a solution also the main issue :P
