### ISSUE TITLE
Regex issue with other wildcard routes

### ISSUE THREAD

**Issue by subhero24** [delvedor/find-my-way#280]
I encoutered an issue with a wildcard route that is not activated if I use a regex in another route.

When I have two routes `/a` and `/*` everything is fine and `/b` will render the wildcard route.
When I change the first route to use a regular expression to match "a", so that I have two routes `/:a(^a)` and `/*`,  the second route will never render and `/b` will result in a 404.

```javascript
const http = require("http");
const router = require("find-my-way")();

router.on("GET", "/:a(^a)", (req, res, params) => {
	res.end("a");
});

// This will not be used with a request to /b ??
router.on("GET", "/*", (req, res, params) => {
	res.end("*");
});

const server = http.createServer((req, res) => {
	router.lookup(req, res);
});

server.listen(1234, (err) => {
	if (err) throw err;
	console.log("Server listening on: http://localhost:1234");
});
```

**Comment by ivan-tymoshenko** [comment]
Hi, nice finding. Would you like to create a PR to fix it?

**Comment by subhero24** [comment]
Will try to create a PR for this.

As I am looking through the code, I have another question: is it expected behaviour to throw when defining two routes like this? Is only one regex allowed for every url part?

```javascript
	findMyWay.on("GET", "/:a(a)", () => {});
	findMyWay.on("GET", "/:b(b)", () => {});
```

**Comment by ivan-tymoshenko** [comment]
https://github.com/delvedor/find-my-way#caveats

**Comment by ivan-tymoshenko** [comment]
The bug that you are trying to fix here:
https://github.com/delvedor/find-my-way/blob/a59117d0daf351429919d586e5edea4ef6d2a14b/index.js#L471

**Comment by subhero24** [comment]
@ivan-tymoshenko 

But should the following be allowed according to the caveats?

```javascript
findMyWay.on('GET', '/:a(a)', () => {})
findMyWay.on('GET', '/:b(b)/static', () => {})
```

Cause matching this to `/b/static` fails

**Comment by ivan-tymoshenko** [comment]
Can you open separate issue for that?

**Comment by subhero24** [comment]
It would seems very limiting to not be able to do this. 

Do we need to prioritise them? could we keep these route parameters in the order they are registered?

**Comment by subhero24** [comment]
Maybe prioritise the more specific routes first (ie more segments vs less segments, more static segments vs parametric segments, etc)?

**Comment by ivan-tymoshenko** [comment]
IMHO, we can't say that one route is preferable to another using anything other than the length of static prefix or node type.

What we can do is separate the parametric node on the parametric node and regexp parametric node and handle the regexp parametric node before the parametric node. It will allow us to add one parametric node and one regexp node. But only one. IDK, if it is worth it.

**Comment by ivan-tymoshenko** [comment]
Can you open a new issue for this bug and describe it there?
