### ISSUE TITLE
v6.0.0. Performance increase

### ISSUE THREAD

**Issue by ivan-tymoshenko** [delvedor/find-my-way#288]
Since version 6.0.0 was released, I want to publish a performance comparison between versions 5.0.0 and 6.0.0.
Thanks, everyone, for your help.

<img width="742" alt="Снимок экрана 2022-05-20 в 21 35 58" src="https://user-images.githubusercontent.com/31734731/169591618-7f242c69-1a30-4bec-9f1f-a48f166e6d57.png">

\* to normalize benchmarks in the main branch, I added querystring parsing (read more [here](https://github.com/delvedor/find-my-way/pull/284#issue-1236322671)).

**Comment by RafaelGSS** [comment]
That's awesome. Definitely, we should make a blog post or at least a tweet announcing that.

**Comment by RafaelGSS** [comment]
@ivan-tymoshenko Would you mind opening a new issue with potential points of improvement? It would help us to make it even faster in future versions.

**Comment by ivan-tymoshenko** [comment]
@RafaelGSS I would like to share the list, but I don't have it. If I got an idea, I'm trying to implement it. Eventually, we will be stuck looping through the path. The overhead is not really big right now.
