### ISSUE TITLE
Static routes optimization

### ISSUE THREAD

**Issue by ivan-tymoshenko** [delvedor/find-my-way#290]
@mcollina Hi, I have an idea for optimizing static paths. But I'm not sure it is worth it. Can you tell me from your experience, or maybe you got some statistics for Fastify:
1) What part of all routes do static routes take?
2) What part of all routes do static routes without querystring params take?

It's not an easy question, but maybe you got something. I have only my developer experience, and it can be not representative.

**Comment by mcollina** [comment]
What do you mean by part?

If you want to do bring this to the next level of perf we might want to generate a full function and get rid of the trie.

**Comment by ivan-tymoshenko** [comment]
By part, I mean usage percentage. What percentage of static routes have in relation to all routes? Maybe static paths are a rare case and most people use parametric routes, so some overhead to optimize static paths is inappropriate.

I'm afraid it will not help. We are stuck looping through a path. Comparing char by char is really slow in comparison with comparing the hole string. It would help if we had the fast native String.startsWith method, but we haven't.

**Comment by mcollina** [comment]
> By part, I mean usage percentage. What percentage of static routes have in relation to all routes? Maybe static paths are a rare case and most people use parametric routes, so some overhead to optimize static paths is inappropriate.

I would not overfocus on static routes, they are _very_ common when using fastify-static or similar, but serving static files with Node.js is a __bad idea__.

**Comment by ivan-tymoshenko** [comment]
The static files case is clear. I'm more interested in the general request case. As I understand the most popular path template is something like `/entities/:id/property`. But maybe I'm wrong and there are a lot of projects that have a lot of static routes.

**Comment by mcollina** [comment]
I agree with you with the exception of first level paths, /, /news, /about, /shop, etc.
