### ISSUE TITLE
how to get matched route path

### ISSUE THREAD

**Issue by JerrysShan** [delvedor/find-my-way#313]
if I register a router 
```
router.on('/api/:id',(req,res)=>{
// how to get matched route path  '/api/:id'

res.end('hello world');
})
```

**Comment by ivan-tymoshenko** [comment]
Hi, you should use another escaping colon char.

`If you just want a path containing a colon without declaring a parameter, use a double colon. For example, /name::customVerb will be interpreted as /name:customVerb`

https://github.com/delvedor/find-my-way#match-order

**Comment by JerrysShan** [comment]
@ivan-tymoshenko Thanks, but I want to get  the register path that match the request path

**Comment by ivan-tymoshenko** [comment]
Then you should escape your parameter with encodeuricomponent function before inserting.

**Comment by ivan-tymoshenko** [comment]
@JerrysShan I'm closing this issue. Feel free to reopen it if you still have some questions.
