### ISSUE TITLE
Get Test Coverage to 100%

### ISSUE THREAD

**Issue by ivan-tymoshenko** [delvedor/find-my-way#330]

**Comment by ivan-tymoshenko** [comment]
@Ekott2006 Hi, I see you are interested in contributing to the project. I really appreciate it. Unfortunately, most of the issues that you can find in the backlog are stuck because they don't have a good answer or the solution doesn't worth it. You can start with this issue. We have a few uncovered lines in the project. Some of them are pretty simple, and some of them require investigation. It's a good issue problem to get familiar with the project. Tell me if you are interested, and I will assign it to you.

**Comment by Ekott2006** [comment]
Let me be honest, I have never used find-my-way before but I am interested to contribute to open source nodejs project. So what exactly am I testing?

**Comment by ivan-tymoshenko** [comment]
you can run `npm test` command. at the end, you will see a test coverage report. There are some lines that are not covered with tests (they marks with red color). You can create a test for them if it's possible or find the reason why they can't be covered (it's possible that there is some redundant code).

**Comment by Ekott2006** [comment]
No problem, I will come back when I face isssues

**Comment by jean-michelet** [comment]
I can give it a try if you want @ivan-tymoshenko

**Comment by ivan-tymoshenko** [comment]
> I can give it a try if you want @ivan-tymoshenko

Go ahead. This is still an actual issue.
