### ISSUE TITLE
Add `has` method

### ISSUE THREAD

**Issue by ivan-tymoshenko** [delvedor/find-my-way#332]
See https://github.com/fastify/fastify/pull/4986#issuecomment-1687015746

The `has` method should parse the given path in the same way as [_on](https://github.com/delvedor/find-my-way/blob/ec25619ac06c16f9aabcab54995ce96f91390a62/index.js#L142) method does.

1. It shouldn't modify the the existing tree structure or has any other side effects.
2. Instead of [throwing an error](https://github.com/delvedor/find-my-way/blob/ec25619ac06c16f9aabcab54995ce96f91390a62/index.js#L286) if path exists, the `has` method should return a boolean value here.
3. It shouldn't be a copy/paste. `_on` and `has` methods should reuse the same code or even each other.

**Comment by mcollina** [comment]
+1
