### ISSUE TITLE
feat: expose `params` inside `findRoute`

### ISSUE THREAD

**Issue by climba03003** [delvedor/find-my-way#341]
Since, `find` is used for lookup by the actual URL. It expose the `params` information.
However, in `findRoute`, it is lookup by the dev URL. It doesn't expose the meaningful `params` information to the user.

I know that `find` is exposing the `params` that is actual value extracted from URL.
So, in `findRoute` it should be exposing the dev array in below.
https://github.com/delvedor/find-my-way/blob/a4d92627b818b42cb682fb2c808e1ca694b215f5/lib/handler-storage.js#L26

Related to https://github.com/fastify/fastify/issues/5215

**Comment by Eomm** [comment]
It could simplify this feature too:

- https://github.com/fastify/fastify-swagger/pull/761

**Comment by sf3ris** [comment]
I can try to take a look at this 🙌
