### ISSUE TITLE
Host constraint breaks with 32 handlers

### ISSUE THREAD

**Issue by valeneiko** [delvedor/find-my-way#343]
If I add 32 handlers with host constraints, then none of the handlers will match and no errors are thrown. 

```js
const router = require('find-my-way')();

const N = 32;

for (let i = 0; i < N; i++) {
  const host = `h${i.toString().padStart(2, '0')}`;
  router.on('GET', '/', { constraints: { host } }, () => { });
}

const result = router.find('GET', '/', { host: 'h01' });
console.log(result); // --> null
```

If I change `N` to `33` then error is thrown from the code below:
https://github.com/delvedor/find-my-way/blob/ca54d8df63efe051c363f29a99aa81c7d9e76fb5/lib/handler-storage.js#L50-L52

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.
