### ISSUE TITLE
Incompatibility with Cloudflare due to using assert instead of node:assert

### ISSUE THREAD

**Issue by SavaCool122** [delvedor/find-my-way#346]
Cloudflare has support for some Node.js packages ([link](https://developers.cloudflare.com/workers/runtime-apis/nodejs/)). There is support for `assert` package, but as I understand it only with the use of `node:` prefix (like `node:assert`). I am not an expert in Node.js , but maybe there is a possibility to add this prefix? I would be happy to do it myself if this option is suitable for CloudFlare support of your codebase.

**Comment by mcollina** [comment]
Unfortunately we support some old node versions that do not support the node: prefix. If I get a PR, I'll land it for the next major.

**Comment by SavaCool122** [comment]
That sounds great to me. I'll be happy to create this PR

**Comment by SavaCool122** [comment]
Here's the PR #347. If any edits are needed, I'd be happy to hear about them
