### ISSUE TITLE
Wildcard route without trailing slash has wrong params

### ISSUE THREAD

**Issue by nwoltman** [delvedor/find-my-way#46]
See [this RunKit](https://runkit.com/embed/zzyyia5a68va).

```js
const router = require('find-my-way')()

router.get('/static/*', function fn () { })

router.find('GET', '/static/').params // {'*': ''}
router.find('GET', '/static').params // {'*': 'static'}
```

Expected `params` to be `{'*': ''}` both times (or `/static` not to match the route, similar to the functionality for `/static/:param`).

(I do think that `find-my-way` should treat routes the same whether they have a trailing slash or not, but that's a separate issue.)

**Comment by delvedor** [comment]
Hi! Thank you for contributing!
Looks like you have found a bug, I'm working on it :)

**Comment by nwoltman** [comment]
Wow that was a fast fix! Thanks @delvedor!
