### ISSUE TITLE
Regex groups seem to break it

### ISSUE THREAD

**Issue by mafintosh** [delvedor/find-my-way#62]
Had a  regex with a group inside which breaks the parsing `/foo/:id(([a-f0-9]{32},?)+)`

``` js
var find = require('find-my-way')()

find.get('/foo/:id(([a-f0-9]{32},?)+)', function () {})
```

**Comment by delvedor** [comment]
Currently I have no time to fix this, I'll give it a try asap.
If you can please send a pr! :)
Same for #63.
