### ISSUE TITLE
repeated code for method and path validation

### ISSUE THREAD

**Issue by psmarsh** [delvedor/find-my-way#69]
Hi! Newbie coder here trying to learn stuff. I noticed that this code to validate paths is repeated twice, once in Router.prototype.off and once in Router.prototype.on:
```
assert(typeof path === 'string', 'Path should be a string')
assert(path.length > 0, 'The path could not be empty')
assert(path[0] === '/' || path[0] === '*', 'The first character of a path should be `/` or `*`')
```

Also, this code to validate methods is repeated twice, once in Router.prototype.off and once in Router.prototype._on:
```
assert(typeof method === 'string', 'Method should be a string')
assert(httpMethods.indexOf(method) !== -1, `Method '${method}' is not an http method.`)
```

Would it make sense to refactor these into functions, e.g. validatePath() and validateMethod()?

**Comment by delvedor** [comment]
Hi! Thank you for checking out the project!
It could make sense, but since we are talking about of just three lines of code I think we can leave them as they are :)

**Comment by mcollina** [comment]
Wrapping them in a function would mean that the stacktrace would not show the culprit function, but one level deep. This would be a good trade off if we had to repeat those several times, but for two repetition it is not worth it.

**Comment by psmarsh** [comment]
Ah gotcha, that explanation makes sense mcollina, thanks
