### ISSUE TITLE
Splitting on `;` instead of `?`

### ISSUE THREAD

**Issue by jsumners** [delvedor/find-my-way#76]
It looks like some vendors use `;` instead of `?` to separate the path from the query string. This is wrong per spec:

> The query component contains non-hierarchical data that, along with
   data in the path component (Section 3.3), serves to identify a
   resource within the scope of the URI's scheme and naming authority
   (if any).  The query component is indicated by the first question
   mark ("?") character and terminated by a number sign ("#") character
   or by the end of the URI.
https://tools.ietf.org/html/rfc3986#section-3.4

But I can tell you that it is out there. So the following should also look for character code 59 as an initial separator.

https://github.com/delvedor/find-my-way/blob/933b63fc23c59c9cc84924308478d28587102108/index.js#L446

**Comment by delvedor** [comment]
:weary:

Thank you for pointing out, would you mind send a pr?

**Comment by delvedor** [comment]
Closed in #77 .
