### ISSUE TITLE
Bug: parametrised regex being bypassed

### ISSUE THREAD

**Issue by kiramdany** [delvedor/find-my-way#80]
The regex for route 2 and 3 of the below code shouldn't match but I am getting the following responses

| | Route | Response |
| --- | --- | --- |
| 1 | /non-trailing-path | {"1: Non trailing path": { path1: 'non-trailing-path' }} |
| 2 | /non-localised/ | {"2: trailing localised": { locale2: 'non-localised' }} |
| 3 | /non-localised/wildcard | {"3: trailing localised with wildcard": { locale3: 'non-localised', '*': 'wildcard' }} |

```
const http = require('http')
const inspect = require('util').inspect
const router = require('find-my-way')()

/* 1 */
router.on('GET', '/:path1', (req, res, params) => {
  res.end(`{"1: Non trailing path": ${inspect(params)}}`)
})
/* 2 */
router.on('GET', '/:locale2(^[a-z]{2}-[a-z]{2}$)/', (req, res, params) => {
  res.end(`{"2: trailing localised": ${inspect(params)}}`)
})
/* 3 */
router.on('GET', '/:locale3(^[a-z]{2}-[a-z]{2}$)/*', (req, res, params) => {
  res.end(`{"3: trailing localised with wildcard": ${inspect(params)}}`)
})

const server = http.createServer((req, res) => {
  router.lookup(req, res)
})

console.log(
    router.prettyPrint()
);
server.listen(3000, err => {
  if (err) throw err
  console.log('Server listening on: http://localhost:3000')
})
```

**Comment by kiramdany** [comment]
I have also noticed a similar issue with the following routes (route 2 and 3 the same as in the original issue)

```
/* 0 */
router.on('GET', '*', (req, res, params) => {
  res.end(`{"0: catch all": ${inspect(params)}}`)
})
/* 2 */
router.on('GET', '/:locale2(^[a-z]{2}-[a-z]{2}$)/', (req, res, params) => {
  res.end(`{"2: trailing localised": ${inspect(params)}}`)
})
/* 3 */
router.on('GET', '/:locale3(^[a-z]{2}-[a-z]{2}$)/*', (req, res, params) => {
  res.end(`{"3: trailing localised with wildcard": ${inspect(params)}}`)
})
```

| | Route | Response |
| --- | --- | --- |
| 0a | /catch-all | _No response_ |
| 0b | /en-gb | {"0: catch all": { '*': '/en-gb' }} |
| 2a | /non-localised/ | _No response_ |
| 2b | /en-gb/ | {"2: trailing localised": { locale2: 'en-gb' }} |
| 3a | /non-localised/wildcard | _No response_ |
| 3b | /en-gb/wildcard | {"3: trailing localised with wildcard": { locale3: 'en-gb', '*': 'wildcard' }} |

Routes 2 and 3 working as expected, however regex also being applied to route 0 which is unexpected

**Comment by jaschaio** [comment]
I am having the exact same problem.

What if I have multiple, ambigious parameter names?

e.G. a route like `/4257` that should resolve to `/:id` and another route like `/about` that should resolve to `/:page`.

My thought was to make this with regex patterns like described by @kiramdany but I get:

```
Method 'GET' already declared for route '/:' with constraints '{}'
```

**Comment by kiramdany** [comment]
@jaschaio 
Just been looking at this library again recently. Seems that's a known caveat of the library unfortunately https://github.com/delvedor/find-my-way#caveats

**Comment by bugagashenkj** [comment]
Can we close it?
