### ISSUE TITLE
weird pretty-print of routes

### ISSUE THREAD

**Issue by AVVS** [delvedor/find-my-way#82]
Please check the screenshots, looks like just a glitch with the names

<img width="282" alt="screen shot 2018-06-28 at 12 28 40 pm" src="https://user-images.githubusercontent.com/1713617/42056378-dbdac488-7ace-11e8-8476-35b093494462.png">
<img width="584" alt="screen shot 2018-06-28 at 12 28 33 pm" src="https://user-images.githubusercontent.com/1713617/42056379-dbf7d9d8-7ace-11e8-9636-dbb6da79b16a.png">

**Comment by mcollina** [comment]
Nice finding! Would you like to help out with a PR?

**Comment by AVVS** [comment]
I don't know about the time I can devote to it right now, though if nobody tackles it I can definitely give it a go

**Comment by delvedor** [comment]
Thanks for reporting this!
If we want to fix this we might want to refactor that function to use [`node-archy`](https://github.com/substack/node-archy) which will simplify the code.

**Comment by mcollina** [comment]
awesome!

Il giorno sab 15 set 2018 alle 05:23 PoppinL <notifications@github.com> ha
scritto:

**Comment by delvedor** [comment]
@poppinlp thanks!
Actually, I don't know if we want to support this feature in the future.
Before work on it, I would suggest waiting for https://github.com/delvedor/find-my-way/pull/89, which will change the internals a lot.

**Comment by delvedor** [comment]
You can open a pr, but #89 will change completely how `find-my-way` works internally, and eventually, we will remove the `prettyPrint` API.
