### ISSUE TITLE
Unexpected route order

### ISSUE THREAD

**Issue by allevo** [delvedor/find-my-way#90]
Hi!

The [readme](https://github.com/delvedor/find-my-way#match-order) explains very well the route order.
In particular the parametric routes go before the parametric ones with regexp.

Using the following code,

```js
function handler (req, res, params) {
  console.log(params)
}
const findMyWay = new FindMyWay({ defaultRoute: notFoundHandler })

findMyWay.on('GET', '/:userId/foo/bar', handler)
findMyWay.on('GET', '/33/:a(^.*$)/:b', handler)

findMyWay.lookup({ url: '/33/foo/bar', method: 'GET', headers: {} }, _res)
```

The regexp route should come after the parametric one and the expected output should be
```
{ userId: "33" }
```

Instead the output is
```
{ a: 'foo', b: 'bar' }
```

Am I wrong in reading the readme?

I'm able to push a failing test in a PR if it helps

**Comment by dcousens** [comment]
It may be that your `33` is static?  And that has precedence?

**Comment by dcousens** [comment]
That appears to be it.

``` js
function notFoundHandler () {}
function handler (req, res, params) {
    console.log(params)
}

const FindMyWay = require('find-my-way')

const findMyWay = new FindMyWay({ defaultRoute: notFoundHandler })
findMyWay.on('GET', '/:userId/foo/bar', handler)
findMyWay.on('GET', '/33/:a(^.*$)/:b', handler)
findMyWay.lookup({ url: '/33/foo/bar', method: 'GET', headers: {} }, () => {})
// { a: 'foo', b: 'bar' }

const findMyWay2 = new FindMyWay({ defaultRoute: notFoundHandler })
findMyWay2.on('GET', '/foo/bar/:userId', handler)
findMyWay2.on('GET', '/:a(^.*$)/:b/33', handler)
findMyWay2.lookup({ url: '/foo/bar/33', method: 'GET', headers: {} }, () => {})
// { userId: '33' }
```

**Comment by allevo** [comment]
Thanks, I'll

**Comment by delvedor** [comment]
This behavior is correct, we are matching every chunk between the slashes in order.

> In particular the parametric routes go before the parametric ones with regexp.

This is true, but we run the check for every node in the current level and not the entire route.
