### ISSUE TITLE
`versions` param not work for create Node instance.

### ISSUE THREAD

**Issue by poppinlp** [delvedor/find-my-way#93]
Hi.

The screenshot is part of [`node.js`](https://github.com/delvedor/find-my-way/blob/master/node.js#L17) file in this repo which we could see the `versions` param is not using in creating. `this.versions` get a new semver store instance every time.

![image](https://user-images.githubusercontent.com/1970625/45252945-265c1980-b391-11e8-9f77-fa5ad3997e46.png)

This will lead to a wrong result for [split node in insert function](https://github.com/delvedor/find-my-way/blob/master/index.js#L190) which showing in the following screenshot. And makes [this issue in fastify](https://github.com/fastify/fastify/issues/1143).

![image](https://user-images.githubusercontent.com/1970625/45253016-74bde800-b392-11e8-9a60-ffe95b83473e.png)

If you'd like, i'll send a PR for this. :)

**Comment by poppinlp** [comment]
By the way, why not move the `test/issue-*.test.js` into your classified test case files since they are ready hard to know the content when just see the file name(the issue number could be commented in test case)?

**Comment by delvedor** [comment]
https://github.com/delvedor/find-my-way/pull/94
