### ISSUE TITLE
parameters' case not preserved in case insensitive mode

### ISSUE THREAD

**Issue by misterdjules** [delvedor/find-my-way#98]
When passing parameters values to route handlers, find-my-way doesn't preserve the case of the actual parameters:

```
$ cat index.js 
const util = require('util');

const router = require('find-my-way')({
  caseSensitive: false
});

const routePatterns = [
  '/foo/:bar'
];

routePatterns.forEach(function addRoute(routePattern) {
  router.on('GET', routePattern, (req, res, params) => {
    if (params) {
      console.log('params:', util.inspect(params, {depth: null}));
    }
  });

});

router.lookup({ method: 'GET', url: '/FOO/BAR', headers: {} }, null);
$ node --version
v6.14.3
$ node index.js 
params: { bar: 'bar' }
$ 
```

In the output above, I would expect the _value_ of the parameter `bar` to be `BAR`, not `bar`.

Looking at [some of the case insensitive tests](https://github.com/delvedor/find-my-way/blob/master/test/case-insesitive.test.js#L41-L56), this seems intentional. However in general it seems counter-intuitive.

It seems it'd make more sense to preserve the original case and let the customer of find-my-way figure out whether and how they want to normalize the parameters values.

Thoughts?

If that makes sense, I have a set of changes that fixes this issue that I can submit as a PR asap.

**Comment by mcollina** [comment]
It was intentional in the sense that when I was writing the code I quickly realized that it would be harder to implement than the current approach, as right now we do a `.toLowerCase()` once, while we would have to do a `.toLowerCase()` at every iteration. 

Definitely 👍 for a PR. We might have to bump the major in that case, but I don't see a bit of a problem with it.

**Comment by misterdjules** [comment]
@mcollina Sounds great! Let me submit the first draft of a PR that I have, and we can iterate on that.

**Comment by misterdjules** [comment]
Submitted at https://github.com/delvedor/find-my-way/pull/99.

**Comment by misterdjules** [comment]
Fixed by https://github.com/delvedor/find-my-way/commit/7a875fd462b208cb7593c8c9fa9fc58c5d95ee3f.
